---
version: 0.3.0
slug: assist_microphone
name: assist_microphone
description: Stream microphone audio to Assist
url: https://github.com/rhasspy/hassio-addons
arch:
  - amd64
  - aarch64
options:
  token: null
  vad: "disabled"
  mic_device: ""
  snd_device: ""
  volume: 1.0
  awake_sound: true
  done_sound: true
  noise_suppression: 0
  auto_gain: 0
  wake_buffer_seconds: 0.0
  udp_mic: false
  debug_logging: false
schema:
  token: str
  vad: list(disabled|webrtcvad|silero)
  mic_device: str
  snd_device: str
  volume: float
  noise_suppression: int
  auto_gain: int
  awake_sound: bool
  done_sound: bool
  wake_buffer_seconds: float
  udp_mic: bool
  debug_logging: bool
init: false
audio: true
homeassistant_api: true
ports:
  "5000/udp": null
homeassistant: 2023.9.0.dev20230809
