---
version: 1.4.0
slug: openwakeword
name: openWakeWord
description: openWakeWord using the Wyoming protocol
url: https://github.com/home-assistant/addons/blob/master/openWakeWord
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
backup_exclude:
  - "*.tflite"
map:
  - share:rw
options:
  model: "ok_nabu"
  threshold: 0.5
  trigger_level: 1
  noise_suppression: 0
  auto_gain: 0
  debug_logging: false
  save_audio: false
schema:
  model: |
    list(ok_nabu|alexa|hey_jarvis|hey_mycroft|hey_rhasspy)
  threshold: float
  trigger_level: int
  noise_suppression: int
  auto_gain: int
  debug_logging: bool
  save_audio: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0.dev20230809
